version: '3.3'

services:
  pg_denormalized:
    build: services/pg_denormalized
    volumes:
      - ./:/tmp/db
      - $HOME/bigdata/pg_denormalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 1344:5432

  pg_normalized_batch:
    build: services/pg_normalized_batch
    volumes:
      - ./:/tmp/db
      - $HOME/bigdata/pg_normalized_batch_2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 1345:5432
